sources:
  - "Source"
templates:
  - "sourcery/templates/AutoCases.stencil"
  - "sourcery/templates/AutoEquatable.stencil"
  - "templates/Introspection.stencil"
  - "templates/AutoJSONDeserializable.stencil"
  - "templates/TypeErase.stencil"
output: "Source/Generated"
